### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Jonyorker** [kyrofa/snap-arch-triplet-generator#2]
Hi,

I am unsure how to use this in my own snapcraft.yaml file.

I have the following app: 

```
apps:
  inspect:
      command: gst-inspect-1.0
      environment:
          LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/home/ubuntu/mysnaps/snaps/parts/tis/install/usr/lib/$SNAP_ARCH_TRIPLETgstreamer-1.0:$SNAP/lib/tcam-0
```

Would my new command become? :

`command: with_snap_arch_triplet gst-inspect-1.0`

Thanks so much!
